alias cp='cp -i'
alias diff='colordiff'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias h='history'
alias j='jobs -l'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lah'
alias ln='ln -i'
alias ls='ls --color=auto'
alias mkdir='mkdir -pv'
alias mv='mv -i'
alias rm='rm -i'
alias path='echo -e ${PATH//:/\\n}'
alias now='date'
alias nowdate='date +"%d-%m-%Y"'
alias ntst='netstat -atulpen'
alias iptb='sudo iptables -vnL --line-numbers'
alias ip6tb='sudo ip6tables -vnL --line-numbers'
